version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: react.Dockerfile
      target: prod
    container_name: react
    expose:
      - '8083'
    ports:
      - '8083:8083'
