import React, { useState, useEffect, MouseEvent, EffectCallback } from 'react';
import { Dispatch, SetStateAction } from 'react';
import {ReactComponent as ReactLogo}  from './tri.svg';
import axios, { AxiosResponse } from 'axios';
import './App.css';
import { GLMSummary } from './types';

const App = () => {
  const [modelRetrieved, setModelRetrieved]: [string, Dispatch<SetStateAction<string>>]  = useState('');
  const [glmSummary, setGlmSummary] = useState<GLMSummary | undefined>(undefined)

  const handleClick = async (event: MouseEvent<HTMLButtonElement>): Promise<GLMSummary> => {
    const res = await axios.get<GLMSummary>('http://localhost:8000/modelsummary/glm/model_0/')
    return res.data
  };

  useEffect(() => {
    setGlmSummary(async () => {
      
    })
  })

  // Store GLM Summary on Click
  // useEffect((handleClick) => { setGlmSummary(handleClick.data) })

  return (
    <div className="App">
      <header>
        <ReactLogo/>
        Enter Model Name
      </header>
      <h5 className="card text-white bg-dark mb-3">Click me damn you!</h5>
      <span className="card-text"> 
      {/* The onClick event is actually generated by React itself: it's a synthetic event.  */}
      <button className="btn btn-outline-primary mx-2 mb-3" style={{'borderRadius':'50px'}}  onClick={handleClick}>Retrieve Models</button>
      </span>
    </div>
  );
}

export default App;