import { ReactComponent as ReactLogo } from './tri.svg';
import './App.css';
import { InfoCard } from './components/home';

const App = () => {
  return (
    <div className="App">
      <header>
        <ReactLogo />
        Enter Model Name
      </header>
      <h5 className="card text-white bg-dark mb-3">Click me damn you!</h5>
      <span className="card-text">
        {/* The onClick event is actually generated by React itself: it's a synthetic event.  */}
        <InfoCard />
      </span>
    </div>
  );
};

export default App;
